### ISSUE TITLE
Node & Musical Performance

### ISSUE THREAD

**Issue by hughrawlinson** [nodeconf/EU-CFP#5]
I could do a talk on musical performance with node.

A little background on me: I'm nearly finished my Music Computing degree at Goldsmiths, moving to work with the Irish startup Soundwave in a few weeks. I (along with two other students here) work on [Meyda](github.com/hughrawlinson/meyda), an Audio Feature Extraction library for the web audio api, and co-authored a paper on it that I presented at the Web Audio Conference in January.

I'm currently working on a live-coding framework for Node, which would provide the basis for my talk. I'd do an introduction to musical live-coding more generally and talk about the influence various frameworks had on my project, and the extra bits I added to play to Javascript's strong points. I would also integrate a short demonstration performance into my talk.

**Comment by mikeal** [comment]
@hughrawlinson we tried to invite you but your github email bounced, can you send me you email addres?

**Comment by hughrawlinson** [comment]
Ah, sorry, I need to change that. hughr2005@gmail.com will work. Thanks!
